apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: gitops-vm
  labels:
    vm-selector: vm-sns7
    gitops-vm-lb: vm-lb-selector
spec:
  className: best-effort-small
  # Friendly image name: noble-server-cloudimg-amd64
  imageName: vmi-18fc3e8b6b5468583
  storageClass: site-a-vsan-supervisor-default-storage-policy
  powerState: PoweredOn
  volumes:
    - name: gitops-vm-pvc-0
      persistentVolumeClaim:
        claimName: gitops-vm-pvc-0
  network:
    interfaces:
      - name: eth0
        network:
          name: vm-default
          kind: SubnetSet
  bootstrap:
    cloudInit:
      rawCloudConfig:
        name: gitops-vm-bootstrap-secret
        key: user-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: gitops-vm-pvc-0
  labels:
    vm-selector: gitops-vm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: site-a-vsan-supervisor-default-storage-policy
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-vm-bootstrap-secret
  labels:
    vm-selector: gitops-vm
stringData:
  user-data: |
    #cloud-config
    
    package_update: true
    package_upgrade: false
    
    # 1. User Configuration
    users:
      - name: demouser
        sudo: ['ALL=(ALL) NOPASSWD:ALL']
        groups: sudo
        shell: /bin/bash
        lock_passwd: false
        # Password: VMware1!
        passwd: "$6$XlPaQkGtoUOWqfKz$Jb3uBcfTpIIskc3oFGZYwyaqRCDp..Q7EGvAkEAlb5hv.la5MCaBd1OxjOJJstEE78LoXsR2QByXsfCmXFNZ11"
        ssh_authorized_keys:
          - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIEtqyiYiaILm5EZsePdG8zmdi5xF1M3/H/pYMLIX0Ua0AAAAC3NzaDpkZXZfa2V5 ssh:dev_key
