apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-vm-exmaple
spec:
  destination:
    name: supervisor-ns-acme-staging-fjdfm
    namespace: acme-staging-fjdfm
  project: infra
  source:
    path: virtualmachine/source
    repoURL: https://github.com/warroyo/vks-argocd-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
